# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
    # Localization settings:

# The generator keeps internal market settings in English so category, brand, price, margin, and seasonality
# dictionaries can be joined reliably. The dictionaries below translate only the values saved in output files.

supported_languages = {"en", "pl"}

category_translations = {
    "Electronics": "Elektronika",
    "Clothing": "Odzież",
    "Home & Garden": "Dom i ogród",
    "Sports": "Sport",
    "Beauty": "Uroda",
    "Toys": "Zabawki",
    "Automotive": "Motoryzacja",
    "Books & Media": "Książki i media",
    "Health": "Zdrowie",
    "Pet Supplies": "Artykuły dla zwierząt",
    "Baby & Kids": "Dziecko",
    "Office": "Biuro",
    "Jewelry & Accessories": "Biżuteria i akcesoria",
    "Furniture": "Meble",
    "DIY Tools": "Narzędzia",
}

product_type_translations = {
    "Smartphone": "Smartfon",
    "Laptop": "Laptop",
    "Wireless Mouse": "Mysz bezprzewodowa",
    "Headphones": "Słuchawki",
    "Printer": "Drukarka",
    "Sneakers": "Sneakersy",
    "T-Shirt": "T-shirt",
    "Jeans": "Jeansy",
    "Jacket": "Kurtka",
    "Dress": "Sukienka",
    "Vacuum Cleaner": "Odkurzacz",
    "Coffee Machine": "Ekspres do kawy",
    "Garden Tool": "Narzędzie ogrodowe",
    "Kitchen Pan": "Patelnia",
    "Desk Lamp": "Lampka biurkowa",
    "Running Shoes": "Buty do biegania",
    "Fitness Mat": "Mata fitness",
    "Mountain Bike": "Rower górski",
    "Tennis Racket": "Rakieta tenisowa",
    "Backpack": "Plecak",
    "Face Cream": "Krem do twarzy",
    "Mascara": "Tusz do rzęs",
    "Shampoo": "Szampon",
    "Perfume": "Perfumy",
    "Lipstick": "Pomadka",
    "Building Blocks": "Klocki",
    "Board Game": "Gra planszowa",
    "Doll": "Lalka",
    "Toy Car": "Samochodzik",
    "Engine Oil": "Olej silnikowy",
    "Car Tire": "Opona samochodowa",
    "Brake Pads": "Klocki hamulcowe",
    "Car Battery": "Akumulator samochodowy",
    "Wiper Blades": "Wycieraczki",
    "Book": "Książka",
    "Comic Book": "Komiks",
    "Music Album": "Album muzyczny",
    "Board Book": "Książeczka kartonowa",
    "Vitamin Supplement": "Suplement witaminowy",
    "Pain Relief": "Lek przeciwbólowy",
    "Toothpaste": "Pasta do zębów",
    "Blood Pressure Monitor": "Ciśnieniomierz",
    "Cold Remedy": "Preparat na przeziębienie",
    "Dog Food": "Karma dla psa",
    "Cat Food": "Karma dla kota",
    "Pet Toy": "Zabawka dla zwierząt",
    "Pet Litter": "Żwirek dla kota",
    "Diapers": "Pieluchy",
    "Baby Formula": "Mleko modyfikowane",
    "Baby Bottle": "Butelka dla dziecka",
    "Car Seat": "Fotelik samochodowy",
    "Baby Stroller": "Wózek dziecięcy",
    "Notebook": "Notes",
    "Pen": "Długopis",
    "Office Chair": "Krzesło biurowe",
    "Monitor": "Monitor",
    "Paper Shredder": "Niszczarka",
    "Watch": "Zegarek",
    "Sunglasses": "Okulary przeciwsłoneczne",
    "Bracelet": "Bransoletka",
    "Handbag": "Torebka",
    "Office Desk": "Biurko",
    "Sofa": "Sofa",
    "Dining Chair": "Krzesło do jadalni",
    "Mattress": "Materac",
    "Wardrobe": "Szafa",
    "Cordless Drill": "Wiertarko-wkrętarka",
    "Screwdriver Set": "Zestaw śrubokrętów",
    "Angle Grinder": "Szlifierka kątowa",
    "Tool Box": "Skrzynka narzędziowa",
    "Saw": "Piła",
}

subcategory_translations = {
    "Mobile Phones": "Telefony komórkowe",
    "Computers": "Komputery",
    "Computer Accessories": "Akcesoria komputerowe",
    "Audio": "Audio",
    "Printing": "Drukowanie",
    "Lifestyle Footwear": "Obuwie lifestyle",
    "Casualwear": "Odzież codzienna",
    "Denim": "Denim",
    "Outerwear": "Odzież wierzchnia",
    "Women's Clothing": "Odzież damska",
    "Home Appliances": "AGD",
    "Kitchen Appliances": "AGD kuchenne",
    "Garden Equipment": "Wyposażenie ogrodu",
    "Cookware": "Naczynia kuchenne",
    "Lighting": "Oświetlenie",
    "Sports Footwear": "Obuwie sportowe",
    "Fitness Equipment": "Sprzęt fitness",
    "Cycling": "Rowery",
    "Racket Sports": "Sporty rakietowe",
    "Outdoor Accessories": "Akcesoria outdoorowe",
    "Face Care": "Pielęgnacja twarzy",
    "Makeup": "Makijaż",
    "Hair Care": "Pielęgnacja włosów",
    "Fragrance": "Zapachy",
    "Construction Toys": "Zabawki konstrukcyjne",
    "Family Games": "Gry rodzinne",
    "Dolls": "Lalki i akcesoria",
    "Vehicles and Tracks": "Pojazdy i tory",
    "Fluids and Lubricants": "Płyny i oleje",
    "Tires": "Opony",
    "Brake System": "Układ hamulcowy",
    "Electrical System": "Układ elektryczny",
    "Visibility": "Widoczność",
    "Literature and Non-Fiction": "Literatura i literatura faktu",
    "Comics and Manga": "Komiksy i manga",
    "Music": "Muzyka",
    "Children's Books": "Książki dziecięce",
    "Supplements": "Suplementy",
    "OTC Medicines": "Leki bez recepty",
    "Oral Care": "Higiena jamy ustnej",
    "Medical Devices": "Urządzenia medyczne",
    "Cold and Flu": "Przeziębienie i grypa",
    "Dog Nutrition": "Żywienie psów",
    "Cat Nutrition": "Żywienie kotów",
    "Pet Accessories": "Akcesoria dla zwierząt",
    "Cat Hygiene": "Higiena kota",
    "Baby Hygiene": "Higiena dziecka",
    "Baby Food": "Żywienie dziecka",
    "Feeding": "Karmienie",
    "Child Safety": "Bezpieczeństwo dziecka",
    "Strollers": "Wózki dziecięce",
    "Paper Products": "Artykuły papiernicze",
    "Writing Instruments": "Artykuły piśmiennicze",
    "Office Furniture": "Meble biurowe",
    "Office Electronics": "Elektronika biurowa",
    "Office Equipment": "Wyposażenie biura",
    "Watches": "Zegarki",
    "Eyewear": "Okulary",
    "Jewelry": "Biżuteria",
    "Bags": "Torby i torebki",
    "Living Room Furniture": "Meble do salonu",
    "Dining Room Furniture": "Meble do jadalni",
    "Bedroom": "Sypialnia",
    "Storage": "Przechowywanie",
    "Power Tools": "Elektronarzędzia",
    "Hand Tools": "Narzędzia ręczne",
    "Workshop Storage": "Przechowywanie narzędzi",
    "Cutting Tools": "Narzędzia tnące",
}

product_series_translations = {
    "Academic": "Akademicka",
    "Akademicka": "Akademicka",
    "Akademia Madrego Dziecka": "Akademia Mądrego Dziecka",
    "Asteriks": "Asteriks",
    "Biblioteczka Opracowan": "Biblioteczka Opracowań",
    "Dla poczatkujacych": "Dla początkujących",
    "Disney Baby": "Disney Baby",
    "Children": "Dziecięca",
    "History": "Historia",
    "Horyzont": "Horyzont",
    "Kids": "Dziecięca",
    "Koncerty": "Koncerty",
    "Litera Nova": "Litera Nova",
    "Polska Muzyka": "Polska Muzyka",
    "Polish": "Polska",
    "Programowanie": "Programowanie",
    "Slowniki": "Słowniki",
    "Wehikul Czasu": "Wehikuł Czasu",
}

product_model_translations = {
    "Alphabet": "Alfabet",
    "Animals": "Zwierzęta",
    "Business": "Biznes",
    "CD": "CD",
    "Collection": "Kolekcja",
    "Colors": "Kolory",
    "Dictionary": "Słownik",
    "Edition": "Wydanie",
    "Guide": "Poradnik",
    "Hits": "Hity",
    "Live": "Koncert",
    "Novel": "Powieść",
    "Numbers": "Liczby",
    "Picture": "Obrazkowa",
    "Reportage": "Reportaż",
    "Story": "Opowieść",
    "Textbook": "Podręcznik",
    "Volume 1": "Tom 1",
    "Volume 2": "Tom 2",
    "Vinyl": "Winyl",
    "Year One": "Rok pierwszy",
    "Algorytmy w Pythonie": "Algorytmy w Pythonie",
    "Alfabet przedszkolaka": "Alfabet przedszkolaka",
    "Atomic Habits": "Atomic Habits",
    "Asteriks i Kleopatra": "Asteriks i Kleopatra",
    "Asteriks u Brytow": "Asteriks u Brytów",
    "Beksinscy. Portret podwojny": "Beksińscy. Portret podwójny",
    "Chlopki. Opowiesc o naszych babkach": "Chłopki. Opowieść o naszych babkach",
    "Diuna": "Diuna",
    "Esencjalista": "Esencjalista",
    "Finansowa forteca": "Finansowa forteca",
    "Fundacja": "Fundacja",
    "Glukozowa rewolucja": "Glukozowa rewolucja",
    "Historia filozofii": "Historia filozofii",
    "Homo deus": "Homo deus",
    "Kajs. Opowiesc o Gornym Slasku": "Kajś. Opowieść o Górnym Śląsku",
    "Kubus i przyjaciele. Liczby": "Kubuś i przyjaciele. Liczby",
    "Lalka": "Lalka",
    "Live Pol'and'Rock": "Live Pol'and'Rock",
    "Maanam The Best": "Maanam The Best",
    "Moj pierwszy slownik obrazkowy": "Mój pierwszy słownik obrazkowy",
    "Myszka Miki. Moje pierwsze slowa": "Myszka Miki. Moje pierwsze słowa",
    "Ostatnie lowy Kravena": "Ostatnie łowy Kravena",
    "Pierwsze slowa. Kolory": "Pierwsze słowa. Kolory",
    "Pierwsze slowa. Zwierzeta": "Pierwsze słowa. Zwierzęta",
    "Paddington. Moje pierwsze slowa": "Paddington. Moje pierwsze słowa",
    "Po prostu Python": "Po prostu Python",
    "Python. Kurs dla nauczycieli i studentow": "Python. Kurs dla nauczycieli i studentów",
    "Republika 82-85": "Republika 82-85",
    "Sapiens. Od zwierzat do bogow": "Sapiens. Od zwierząt do bogów",
    "Slownik angielsko-polski polsko-angielski": "Słownik angielsko-polski polsko-angielski",
    "Socjologia. Analiza spoleczenstwa": "Socjologia. Analiza społeczeństwa",
    "Szkola latania": "Szkoła latania",
    "Wielka trwoga": "Wielka trwoga",
    "Wielki slownik polsko-angielski Oxford": "Wielki słownik polsko-angielski Oxford",
    "Wielki turniej": "Wielki turniej",
    "Wojna bez konca": "Wojna bez końca",
    "Zbrodnia i kara": "Zbrodnia i kara",
}

product_name_translations = {
    "PWN Slownik angielsko-polski polsko-angielski": "PWN Słownik angielsko-polski polsko-angielski",
    "Znak Beksinscy. Portret podwojny": "Znak Beksińscy. Portret podwójny",
    "Helion Python. Kurs dla nauczycieli i studentow": "Helion Python. Kurs dla nauczycieli i studentów",
    "Egmont Kajko i Kokosz Szkola latania": "Egmont Kajko i Kokosz Szkoła latania",
    "Egmont Akademia Madrego Dziecka Pierwsze slowa. Zwierzeta": "Egmont Akademia Mądrego Dziecka Pierwsze słowa. Zwierzęta",
    "Mlekovita Maslo Polskie 200 g": "Mlekovita Masło Polskie 200 g",
    "Kotlin Ketchup Lagodny 450 g": "Kotlin Ketchup Łagodny 450 g",
    "Doppelherz Aktiv Magnez B6 30 tabletek": "Doppelherz Aktiv Magnez B6 30 tabletek",
}

color_translations = {
    "black": "czarny",
    "white": "biały",
    "gray": "szary",
    "silver": "srebrny",
    "blue": "niebieski",
    "navy": "granatowy",
    "red": "czerwony",
    "green": "zielony",
    "beige": "beżowy",
    "brown": "brązowy",
    "pink": "różowy",
    "yellow": "żółty",
    "orange": "pomarańczowy",
    "purple": "fioletowy",
    "gold": "złoty",
    "multicolor": "wielokolorowy",
}

payment_method_translations = {
    "BLIK": "BLIK",
    "Card": "Karta",
    "Fast transfer": "Szybki przelew",
    "Deferred payment": "Płatność odroczona",
    "COD": "Płatność przy odbiorze",
    "Wallet": "Portfel elektroniczny",
    "Bank transfer": "Przelew bankowy",
}

payment_provider_translations = {
    "PayU": "PayU",
    "Przelewy24": "Przelewy24",
    "Tpay": "Tpay",
    "Autopay": "Autopay",
    "Stripe": "Stripe",
    "PayPal": "PayPal",
    "PayPo": "PayPo",
    "Other": "Inny",
}

delivery_method_translations = {
    "InPost parcel locker": "Paczkomat InPost",
    "InPost courier": "Kurier InPost",
    "DPD": "DPD",
    "DHL": "DHL",
    "Allegro One": "Allegro One",
    "Orlen Paczka": "Orlen Paczka",
    "Poczta Polska": "Poczta Polska",
    "UPS": "UPS",
    "FedEx": "FedEx",
    "Store pickup": "Odbiór w sklepie",
}

gender_translations = {
    "Male": "Mężczyzna",
    "Female": "Kobieta",
}

translations = {
    "pl": {
        "category": category_translations,
        "subcategory": subcategory_translations,
        "product_type": product_type_translations,
        "product_series": product_series_translations,
        "product_model": product_model_translations,
        "product_name": product_name_translations,
        "color": color_translations,
        "payment_method": payment_method_translations,
        "payment_provider": payment_provider_translations,
        "delivery_method": delivery_method_translations,
        "gender": gender_translations,
    },
    "en": {},
}
